name: Build/release
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  pull_request:
    branches:
      - master

jobs:
  Ubuntu-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build/release Electron app
        run: |
          npm install
          npm run-script release

      - name: Post status to Discord
        uses: sarisia/actions-status-discord@v1
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          job: Build
          description: The City of Truro Mariners - Management Console Ubuntu
          nofail: false
          nodetail: false
          color: 0xFFFFFF
          username: Discord CI
          avatar_url: "https://discord.com/assets/6debd47ed13483642cf09e832ed0bc1b.png"

  Windows-Build:
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build/release Electron app
        run: |
          npm install
          npm run-script release

      - name: Post status to Discord
        uses: sarisia/actions-status-discord@v1
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          job: Build
          description: The City of Truro Mariners - Management Console Windows
          nofail: false
          nodetail: false
          color: 0xFFFFFF
          username: Discord CI
          avatar_url: "https://discord.com/assets/6debd47ed13483642cf09e832ed0bc1b.png"

  macOS-Build:
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build/release Electron app
        run: |
          npm install
          npm run release
      
      - name: Post status to Discord
        uses: sarisia/actions-status-discord@v1
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          job: Build
          description: The City of Truro Mariners - Management Console macOS
          nofail: false
          nodetail: false
          color: 0xFFFFFF
          username: Discord CI
          avatar_url: "https://discord.com/assets/6debd47ed13483642cf09e832ed0bc1b.png"